repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.73.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: tflint
- repo: https://github.com/awslabs/git-secrets
  rev: v1.3.1
  hooks:
    - id: git-secrets
