// Required providers are generated by Terragrunt (see terragrunt/_global/terragrunt.hcl)
// This file is intentionally left minimal to avoid duplicate required_providers
terraform {
	required_version = ">= 1.6.0"
}
